apiVersion: apps/v1
kind: Deployment
metadata:
  name: deps
spec:
  replicas: {{ .Values.replicaCount }}  # Usa il valore di replicaCount dal file values.yaml
  selector:
    matchLabels:
      app: deps
  template:
    metadata:
      labels:
        app: deps
    spec:
      containers:
        - name: my-container
          image: nginx:latest  # Immagine di esempio, puoi cambiarla
          ports:
            - containerPort: 80

