apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: {{ .Values.replicaCount }}  # Usa il valore di replicaCount dal file values.yaml
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-container
          image: nginx:latest  # Immagine di esempio, puoi cambiarla
          ports:
            - containerPort: 80

